apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Redis

datasources:
  - name: Prometheus
    type: prometheus
    isDefault: false
    access: proxy
    orgId: 1
    version: 1
    url: ${PROMETHEUS_URL}
    uid: Prometheus
    jsonData:
      timeInterval: 15s
    editable: true
  - name: Redis
    type: redis-datasource
    isDefault: true
    access: proxy
    orgId: 1
    version: 1
    url: redis://secretum-redis:6379
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    editable: true
