global:
  sendAnonymousUsage: false

api:
  dashboard: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: INFO
  format: common

entryPoints:
  http:
    address: ":80"

  ping:
    address: ":8082"

ping:
  entryPoint: ping

metrics:
  prometheus: { }

accessLog: { }
