apiVersion: 1

deleteDatasources:
  - name: Prometheus

datasources:
  - name: Prometheus
    type: prometheus
    isDefault: true
    access: proxy
    url: ${PROMETHEUS_URL}
    uid: Prometheus
    jsonData:
      timeInterval: 15s
